list1=[1,[2,3],[4,5,6]]
list2=[]
"""
using 2 list and getitem and append method
list2=[]
#print(list1[2][2])
y=list1.__getitem__(0)
list2.append(y)
y=list1.__getitem__(1)
z=y.__getitem__(0)
list2.append(z)
z=y.__getitem__(1)
list2.append(z)
y=list1.__getitem__(2)
z=y.__getitem__(0)
list2.append(z)
z=y.__getitem__(1)
list2.append(z)
z=y.__getitem__(2)
list2.append(z)
list1=list2
print(list1)"""
#using pop and append method
y=list1.pop()
z=y.pop()
list2.append(z)
z=y.pop()
list2.append(z)
z=y.pop()
list2.append(z)
y=list1.pop()
z=y.pop()
list2.append(z)
z=y.pop()
list2.append(z)
y=list1.pop()
list2.append(y)
lis1=list2.reverse()
print(list2)